### ISSUE TITLE
Feature: ignore certain actions in the reducer

### ISSUE THREAD

**Issue by nlopin** [frontendphil/react-undo-redo#262]
h2. Context

We work on a drawing tool where users can draw polygons on a map. They can also reposition the vertices of the drawn polygon. A single reducer manages every action.

h2. Problem

When the user moves a vertex, we constantly send actions to the reducer to update the state and rerender the image. At the moment, `react-undo-redo` captures every such action. When users try to undo their action, they do not see the change because it is too small. Only by holding the undo button they can see how the vertex moves back to the previous position

h2. Proposal

Introduce a way to ignore actions and pass them straight to the reducer without putting their state to the undo/redo state.

Possible API:
```ts
const { UndoRedoProvider, usePast, usePresent, useFuture, useUndoRedo } =
  createUndoRedo(reducer, { ignoreActions: ['UPDATE_POINT', 'NON_VISUAL_CHANGE'] })
```

**Comment by nlopin** [comment]
@frontendphil if it sounds good for you, I can implement the change

**Comment by frontendphil** [comment]
Yep, sounds good. I was essentially waiting for this to come up at some point :D I'd suggest something like a `track` callback you can pass to the context provider (which is optional and returns `true` by default) that you can overwrite and which receives every action. When it returns `false` we modify the `present` state but don't push to `past`. Sounds good? Feel free to give it a stab!

**Comment by nlopin** [comment]
The solution with callback requires more code from the user. It is a valid solution when a user has to rely on complex logic. Do you see use cases when the content of this call back will be something except `(action) => ignoredActions.includes(action.type)`? 

The only example which comes to my mind is situation when action do not have `type` property

**Comment by frontendphil** [comment]
Thanks for the PR! I always try to start by not assuming anything about the structure of the code on the other end. However, you're right that a lot of actions will probably have a `type` property. I would still encode this into the helper title. Something like `excludeActionsWithType.` We could make this even nicer (IMO) if we don't require an array but use a spread internally so that you can pass as many actions as parameters as you like. 

```ts
createUndoRedo(reducer, { track: excludeActionsWithType('UPDATE_POINT', 'NON_VISUAL_CHANGE') })
```

Though I'd love the helper to be type-safe, I'm unsure how to do it in this setup. If we'd return the helper from `createUndoRedo` instead and move the `track` option to the provider again, we could export an `excludeActionsWithType` helper that only accepts `type` options that the `reducer` knows about to avoid silly mistakes.

```tsx
const { UndoRedoProvider, excludeActionsWithType } = createUndoRedo(reducer)

const Component = () => (
  <UndoRedoProvider initialState={0} track={excludeActionWithType('UPDATE_POINT', 'NON_VISUAL_CHANGE')}>
    // ...magic
  </UndoRedoProvider>
)
```

WDYT?

**Comment by nlopin** [comment]
I like the `excludeActionsWithType` idea. Let's see if I can try to make such a helper. It would be a separate PR anyways
